# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/jobsemble-backend:$BUILD_ID', '.']
  
  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jobsemble-backend:$BUILD_ID']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'jobsemble-backend'
    - '--image'
    - 'gcr.io/$PROJECT_ID/jobsemble-backend:$BUILD_ID'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '3001'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--set-env-vars'
    - 'CLOUD_PROVIDER=GCP-CLOUD-RUN,SEARCH_BACKEND=tavily,PORT=3001,NODE_ENV=production'
    - '--set-secrets'
    - 'TAVILY_API_KEY=tavily-api-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/jobsemble-backend:$BUILD_ID'
